//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Test.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ---&gt; .
        /// </summary>
        internal static string ARROW_STRING {
            get {
                return ResourceManager.GetString("ARROW_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label &gt; div &gt; div &gt; span.cbx.x-refine__multi-select-cbx.
        /// </summary>
        internal static string BRAND_NAME {
            get {
                return ResourceManager.GetString("BRAND_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label &gt; div &gt; input.
        /// </summary>
        internal static string CHECKBOX_SELECTOR {
            get {
                return ResourceManager.GetString("CHECKBOX_SELECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.ebay.com/.
        /// </summary>
        internal static string EBAY_WEBSITE {
            get {
                return ResourceManager.GetString("EBAY_WEBSITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string ENGLISH_LANGUAGE {
            get {
                return ResourceManager.GetString("ENGLISH_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .x-overlay__wrapper--right.
        /// </summary>
        internal static string MODAL_SELECTOR {
            get {
                return ResourceManager.GetString("MODAL_SELECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [^0-9\.,]+.
        /// </summary>
        internal static string PRICE_REGEX {
            get {
                return ResourceManager.GetString("PRICE_REGEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to srp-river-results-listing.
        /// </summary>
        internal static string PRODUCT_ID {
            get {
                return ResourceManager.GetString("PRODUCT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Product number .
        /// </summary>
        internal static string PRODUCT_NUMBER_STRING {
            get {
                return ResourceManager.GetString("PRODUCT_NUMBER_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n Products found: \n.
        /// </summary>
        internal static string PRODUCTS_FOUND {
            get {
                return ResourceManager.GetString("PRODUCTS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to span.s-item__logisticsCost.
        /// </summary>
        internal static string RAW_LOGICIST_COST_TEXT {
            get {
                return ResourceManager.GetString("RAW_LOGICIST_COST_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.s-item__link &gt; h3.
        /// </summary>
        internal static string RAW_NAME_TEXT {
            get {
                return ResourceManager.GetString("RAW_NAME_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to span.s-item__price.
        /// </summary>
        internal static string RAW_PRICE_TEXT {
            get {
                return ResourceManager.GetString("RAW_PRICE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n Number of results found: .
        /// </summary>
        internal static string RESULTS_FOUND {
            get {
                return ResourceManager.GetString("RESULTS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1.srp-controls__count-heading &gt; span.BOLD.
        /// </summary>
        internal static string RESULTS_SELECTOR {
            get {
                return ResourceManager.GetString("RESULTS_SELECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .x-flyout__button.
        /// </summary>
        internal static string SORT_BUTTON_SELECTOR {
            get {
                return ResourceManager.GetString("SORT_BUTTON_SELECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n Sorting products by name (ascendant): \n.
        /// </summary>
        internal static string SORTING_NAME_OUTPUT {
            get {
                return ResourceManager.GetString("SORTING_NAME_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n Sorting products by price (descendant): \n.
        /// </summary>
        internal static string SORTING_PRICE_DESCENDING {
            get {
                return ResourceManager.GetString("SORTING_PRICE_DESCENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0} | Price (Including Shipping): {1}.
        /// </summary>
        internal static string TO_STRING_OUTPUT {
            get {
                return ResourceManager.GetString("TO_STRING_OUTPUT", resourceCulture);
            }
        }
    }
}
